In [1]:
import numpy as np


In [2]:
arr = np.array([1, 2, 3, 4])


In [3]:
arr + 2  # Adds 2 to each element


array([3, 4, 5, 6])

In [4]:
arr * 2  # Multiplies each element by 2


array([2, 4, 6, 8])

In [5]:
arr * 2  # Multiplies each element by 2


array([2, 4, 6, 8])

In [6]:
np.sum(arr)


10

In [7]:
np.mean(arr)


2.5

In [8]:
arr_reshaped = np.reshape(arr, (2, 2))  # Reshape into a 2x2 array


In [9]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result = np.dot(mat1, mat2)  # Matrix multiplication
