In [1]:
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [2]:
#reshapping array 
# Reshaping the array into 2x3
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


In [3]:
#Array Operations (Element-wise Addition, Multiplication)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
sum_arr = arr1 + arr2
print(sum_arr)

# Element-wise multiplication
prod_arr = arr1 * arr2
print(prod_arr)


[5 7 9]
[ 4 10 18]
